### ISSUE TITLE
Potentially incorrect dependencies

### ISSUE THREAD

**Issue by BastianZim** [conda-forge/langchain-feedstock#155]
### Solution to issue cannot be found in the documentation.

- [X] I checked the documentation.

### Issue

Hi,

I'm managing the evals feedstock where I ran into the following problem: `package langchain-0.0.136-pyhd8ed1ab_0 has constraint openai >=0.0.0,<1.0.0 conflicting with openai-1.0.0-pyhd8ed1ab_0`

I couldn't find this upstream, so could it be that this restriction is incorrect?

Ref: https://dev.azure.com/conda-forge/feedstock-builds/_build/results?buildId=848027&view=logs&j=656edd35-690f-5c53-9ba3-09c10d0bea97&t=986b1512-c876-5f92-0d81-ba851554a0a3&l=172
Feedstock: https://github.com/conda-forge/evals-feedstock/pull/3

Thanks!

**Comment by pavelzw** [comment]
This is fixed now.
https://github.com/conda-forge/langchain-feedstock/blob/b57d9cb14746153a927d5e1967bfa5789e368c0f/recipe/meta.yaml#L52

The issue was probably that the autotick updater was not correctly using grayskull for some reason. I heard that it's been updated internally a bit; maybe these kinds of issues won't happen again.
